apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats-repository
  namespace: flux-system
spec:
  interval: 30m
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nats-namespace
  install:
    createNamespace: true
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats-repository
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
  releaseName: dwk-nats

